### ISSUE TITLE
Cannot build pow

### ISSUE THREAD

**Issue by sebastiendan** [textileio/powergate#204]
The README lists the following command to build `pow` but such path doesn't exist:

```
go build -i -o pow exe/cli/main.go 
```

Tried with both paths under /exe with no success.

**Comment by jsign** [comment]
You're right! It seems that on some renamings that folder got incorrectly renamed.
I created & merged #209, which fixes that and also refreshed a bit the _Readme_ which was stale. It's still pretty dry, but much better than before.

I'm currently working on #186  which will make building and running easier since I will take out all CGO related stuff.

**Comment by jsign** [comment]
@sebastiendan, a lot has happened since your report. The Readme has some new information about building PG. The recommended way is running `make build-cli` for building the CLI. If you want to run the server (and lotus, and ipfs) to use the cli, I'd recommend running `make fresh` standing in the `/docker` folder. Recall that the Lotus node should be synced to be able to use FFS.

**Comment by jsign** [comment]
I'll be closing this issue. Please re-open one if you find some problems using the new workflow.
Thanks for the report!
