### ISSUE TITLE
Docker-compose fail when try to connect to local net

### ISSUE THREAD

**Issue by 524119574** [textileio/powergate#500]
When I run make localnet in the powergate/docker directory I got the following error:
```
powergate_1  | 2020-07-02T20:27:05.448Z	FATAL	powd	powd/main.go:63	starting server: connecting to lotus node: resolving dns: lookup lotus on 127.0.0.11:53: no such host
localnet_powergate_1 exited with code 1
```

I have also seen this error:
```
lotus_1      | panic: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleIncomingBlocks (/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.0/node/modules/services.go:61): failed to build *pubsub.PubSub: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build dtypes.DrandBootstrap: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: lookup _dnsaddr.pl-sin.testnet.drand.sh on 127.0.0.11:53: read udp 127.0.0.1:33566->127.0.0.11:53: i/o timeout
lotus_1      |
lotus_1      | goroutine 1 [running]:
lotus_1      | main.main()
lotus_1      | 	/app/main.go:46 +0x5e0
```
I am using a MAC

**Comment by jsign** [comment]
Thanks for reporting this. Taking a look in the Lotus slack logs, its seems is related to a [DNS problem](https://filecoinproject.slack.com/archives/CP50PPW2X/p1591779599066100).
Let's keep this open to see if you come up with the exact cause of this.

**Comment by AustinFoss** [comment]
I had a similar error when running the same:

`powergate_1  | 2020-07-06T02:51:05.736Z	FATAL	powd	powd/main.go:63	starting server: connecting to lotus node: resolving dns: i/o timeout
`

**Comment by jsign** [comment]
The lotus localnet has a fixed tag `v0.4.0` for ~15 days. 
That last message about Powergate is failing to connect to Lotus is because Lotus is failing to start.

Do you have the same `lotus_1` message: `lotus_1      | panic: starting node: could not build arguments for function "github.com/filecoin-project/lotus...`?

**Comment by peterVG** [comment]
I got the same `lookup lotus on 127.0.0.11:53: no such host localnet_powergate_1 exited with code 1` error with Localnet when I was working offline. Reconnecting to internet fixed it. 

The IPFS and Powergate servers started no problem but the Lotus server kept trying to connect but would fail. It may be because the Lotus server is trying to connect to an external Docker image? See
https://github.com/textileio/powergate/blob/d29673558770a5c99b31cf7cf8ba305717698d84/docker/docker-compose.yaml#L31 Neither the IPFS nor Powergate server have an `image:` tag.

**Comment by asutula** [comment]
IPFS and Powergate images are manages in other compose files in the same directory:

https://github.com/textileio/powergate/blob/master/docker/ipfs-image.yaml#L6
https://github.com/textileio/powergate/blob/master/docker/powergate-image.yaml#L5

and combined with the main `docker-compose.yaml` in the `Makefile`:

https://github.com/textileio/powergate/blob/master/docker/Makefile#L31

**Comment by peterVG** [comment]
Okay, right. So that wasn't it then. But hopefully the failure when disconnected versus success when connected gives you a useful clue? As I noted, that didn't affect the IPFS and Powergate servers. They both went up successfully while disconnected (I'm working from a remote cabin ATM where cellular data fees are astronomical :-)

**Comment by jsign** [comment]
I think there's some lotus packages that try to resolve some drand bootstrap nodes, despite localnet doesn't need to use them.

Unfortunately, that might be in init method of packages which we can't control much.

**Comment by j-mars** [comment]
I am getting the same error as the OP in Windows 10 running docker on WSL 2. This is a WSL 2 error as I have tested in a WSL 1 dev environment and the no such host problem does not appear.

Any clue as to how to solve this ?

**Comment by jsign** [comment]
From some recent version of Lotus, the BLS code has become more _your-own-hardware_ dependant.
Even with docker, if the CPU instruction set where it's built is different from where is ran there's a higher chance that might not be compatible. Thus, `SIGILL: illegal instruction`.

The solution if you're experiencing that, is building a `lotus-devnet` Docker image yourself.
Here're some steps if you want to try it out:
1. git checkout https://github.com/textileio/lotus-devnet/releases/tag/ntwk-calibration-8.8.0
2. make build
3. `docker build -t j my-local-devnet .`
4. In the Powergate repo, replace in `docker/docker-compose-localdevnet.yaml`, the `textile/local-devnet:..` for `my-local-devnet`.

That should make the trick.

**Comment by j-mars** [comment]
> 4\. my-local-devnet

@jsign it worked. So can I assume that this is just one issue which is connected to a hardware dependent problem? And not a DNS issue or some internal Docker networking thing? Because it is still weird that on an WSL 1 environment it all boot ups normally, but on an WSL 2 environment it doesn't.

Thanks for the support

**Comment by jsign** [comment]
> > 4. my-local-devnet
> 
> @jsign it worked. So can I assume that this is just one issue which is connected to a hardware dependent problem? And not a DNS issue or some internal Docker networking thing? Because it is still weird that on an WSL 1 environment it all boot ups normally, but on an WSL 2 environment it doesn't.
> 
> Thanks for the support

The `SIGILL: illegal instruction`, yes, should be. Considering that Windows 10 and WSL 1/2 might do other kinds of magic, there might be other obscure things under the hood.

**Comment by jsign** [comment]
I'll be closing this, if anyone continues to have some problem please file a new issue.
