### ISSUE TITLE
 starting server: creating filecoin host: couldn't connect to any of bootstrap peers

### ISSUE THREAD

**Issue by nathansenn** [textileio/powergate#568]
Trying to connect to the new calibrationnet

![Screen Shot 2020-08-14 at 6 54 55 PM](https://user-images.githubusercontent.com/13710524/90242532-ce24d080-de5f-11ea-8b1c-5c8b95891615.png)

**Comment by jsign** [comment]
Hey @nathansenn . `jsign/calib.8.13.0` is a WIP branch to add support to the new version, so isn't yet ready.

In the process of adding support in Powergate, I discovered a retrieval bug on some file sizes. They were working in a fix, so most probably using 8.13.0 won't be a usable version anyway.

Stay tuned since most prob today we'll have a PR ready for the new calibration.

**Comment by nathansenn** [comment]
#569 This would solve the bootstrap issue for the new calibrationnet

**Comment by jsign** [comment]
Replied on the PR!
