### ISSUE TITLE
"not enough miners" error

### ISSUE THREAD

**Issue by aphelionz** [textileio/powergate#587]
Running the tests on https://github.com/orbitdb/orbit-db-powergate-io with the latest master gives me this error when trying to `pushStorageConfig`

```
{
  id: '5ede2618-23a1-43ec-8037-cdb994621bce',
  apiId: '4e3c1ff3-5686-4b57-8d31-205e5103c04a',
  cid: 'QmPow9VVt34gmSgT1pzJkKBP1YRWrpW98DMFkdKR59m4YX',
  status: 3,
  errCause: 'executing cold-storage config: making deal configs: getting miners from minerselector: not enough miners that satisfy the constraints',
  dealErrorsList: []
}
```

Rolling back to `8c9076dea8ce52e22e26455823f362b560a16aa2` worked for now

**Comment by andrewxhill** [comment]
What was your StorageConfig btw?

**Comment by jsign** [comment]
@aphelionz, my best guess is that now `master` has biased selection towards some trusted miners in `testnet`.
That means that if you use the default _StorageConfig_, it will have `TrustedMiners: [t013204,...]`, which in localnet doesn't work.

I'll confirm this running it myself. In the CI the used _StorageConfig_ isn't the default one, so that's why all is good.
I'll ping back here in some mins with confirmation/fix.

**Comment by aphelionz** [comment]
I was just using the default StorageConfig for now

**Comment by aphelionz** [comment]
sure, trying now :+1:

**Comment by aphelionz** [comment]
Yep, thank you @jsign! This seems to fix it.
